---
title: "Sexual Dimorphism From Sexual Dichromatism"
author: "Sarah E Taylor"
date: "2024-01-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Loading in Data

```{r Load-R-Libraries, include=FALSE}
# Load in the libraries
library(ape)
library(phylolm)
library(tidyverse)
```


```{r Read-Mammal-Tree-Upham, echo=FALSE}
#read in mammal tree
mammaltree <- read.tree("data/Phylo_Project_Data/MamPhy_BDvr_Completed_v2_tree0000.tre")
summary(mammaltree)
```


```{r Read-Masters-Binary-Data, echo=TRUE}
#read in the data
Binary_traits <- read_csv("data/Phylo_Project_Data/Masters_Binary_Traits.csv")
head(Binary_traits)
```

## Format Data

```{r Format-Binary-Data-SpeciesNames, echo=TRUE}
#combine genus and species names and capitalize first letter
Binary_traits_combined = Binary_traits %>% unite("species",`Genus_names`, `species_name`) %>% mutate(species = str_to_title(species))
head(Binary_traits_combined)
```


```{r Prune-Tree-For-Species-in-Data, echo=TRUE}
# prune tree for species in data
species_not_in_tree=setdiff(mammaltree$tip.label, Binary_traits_combined$species)
pruned.tree<-drop.tip(mammaltree,species_not_in_tree)
summary(pruned.tree)
```


```{r Prune-Data-For-Species-From-Tree, echo=TRUE}
#prune data for species in tree
data_pruned = Binary_traits_combined %>% filter(species %in% pruned.tree$tip.label)
head(data_pruned)
```


```{r Format-Data-Phylolm, echo=TRUE}
#put data into useful form for phylolm
colnames(data_pruned) = gsub(" ", "_", colnames(data_pruned))
data_pruned_rownames = column_to_rownames(data_pruned, var = "species")
head(data_pruned_rownames)
```

## Sexual Dimorphism from Sexual Dichromatism Regression

```{r Run-phylolm}
# run phylolm and get summary
SDMfromSDC <- phyloglm(Sexual_Dimorphism ~ Sexual_Dichromatism, data_pruned_rownames, phy = pruned.tree,method="logistic_MPLE")
summary(SDMfromSDC)
```

