---
title: "Cleaning up some of the data"
author: "Sarah E Taylor"
date: "2024-02-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Loading in Data

```{r Libraries, include=FALSE}
library(tidyverse)
library(dplyr)
```


```{r Load in the data}
# Read the CSV file
data <- read_csv("~/GitHub/LocksofLineage/data/Full_Hair_Traits_Updated_Names.csv")

# Remove the incorrect genus names
data$Genus[data$Genus == "procolobus (piliocolobus)"] <- "procolobus"
```

## Code the Data

```{r Binarize the data that is two way}

# Binarize the data
data_test_multiple <- data %>%
  mutate(across(c(Sexual_dimorphism, Natal_coat, Sexual_dichromatism), ~if_else(. == "Yes", 1, 0)))

#Binarize for male selected traits
data_multiple_male <- data_test_multiple %>%
  mutate(across(c(Darker, Direction), ~if_else(. == "M", 1, 0)))

#Separate out the natal coat types
#First: binarize the data for just one type
#Second: add it as a new column to the dataframe
#Third: repeat for all types
#Fourth: Concatenate all the columns into one dataframe

#Incon Data
data_multiple_incon <- data_multiple_male %>%
  mutate(Natal_Coat_Type = if_else(Natal_Coat_Type == "incon", 1, 0))

position <- which(names(data_multiple_incon) == "Natal_Coat_Type") + 1
data_multiple_incon <- add_column(data_multiple_incon, incon = data_multiple_incon$Natal_Coat_Type, .after = position - 1)

#Cond Data
data_multiple_cond <- data_multiple_male %>%
  mutate(Natal_Coat_Type = if_else(Natal_Coat_Type == "Con to dad", 1, 0))

position <- which(names(data_multiple_cond) == "Natal_Coat_Type") + 1
data_multiple_cond <- add_column(data_multiple_cond, ConD = data_multiple_cond$Natal_Coat_Type, .after = position - 1)

#Conm Data
data_multiple_conm <- data_multiple_male %>%
  mutate(Natal_Coat_Type = if_else(Natal_Coat_Type == "con to mom", 1, 0))

position <- which(names(data_multiple_conm) == "Natal_Coat_Type") + 1
data_multiple_conm <- add_column(data_multiple_conm, ConM = data_multiple_conm$Natal_Coat_Type, .after = position - 1)

#Conb Data
data_multiple_conb <- data_multiple_male %>%
  mutate(Natal_Coat_Type = if_else(Natal_Coat_Type == "con to both", 1, 0))

position <- which(names(data_multiple_conb) == "Natal_Coat_Type") + 1
data_multiple_conb <- add_column(data_multiple_conb, ConB = data_multiple_conb$Natal_Coat_Type, .after = position - 1)

# Combining all of the columns into one dataframe
data_binarized <- bind_cols(data_multiple_conb %>% select(family, Genus, species, Sexual_dimorphism, Location, Direction, Natal_coat, ConB, Sexual_dichromatism, Darker),
                    data_multiple_cond %>% select(ConD), data_multiple_conm %>% select(ConM), data_multiple_incon %>% select(incon))

#Binarize the location data to head only for sexual dimorphism
data_binarized <- data_binarized %>%
  mutate(Location = if_else(Location == "Head", 1, 0))

#Rename Columns to be more descriptive
data_binarized <- data_binarized %>%
  rename(Direction_Male = Direction,
         Darker_Male = Darker,
         SD_Location_Head = Location)

```

```{r Other ways to binarize, include=FALSE}
#Binarize the data keeping the NAs
#data_test_SC_NA <- data_test_multiple %>%
#mutate(
# Sexual_dichromatism_type = if_else(Sexual_dichromatism_type == "Complete", 1, 0)
#  )
```

```{r Code the columns that are not two way}
#data_multiple_options <- data_test_SC_NA %>%
  #mutate(Darker = match(Darker, unique(Darker)))

data_multiple_multiple <- data_test_multiple %>%
  mutate(across(c(Darker, Direction, Natal_Coat_Type), ~match(., unique(.)) - 1))

write.csv(data_multiple_multiple, "~/Github/LocksofLineage/data/data_multiple_multiple.csv", row.names = FALSE)

#data_multiple_options <- data %>%
  #mutate(Darker = if_else(is.na(Darker), NA_integer_, match(Darker, unique(Darker))))
```

```{r Create new binary data file}
write.csv(data_binarized, "~/GitHub/LocksofLineage/data/data_binarized_Feb13.csv", row.names = FALSE)
```

## Create the Legend

```{r Create the Legend}
#Create the legend function
create_legend <- function(column) {
  unique_values <- unique(column)
  encoded_values <- match(unique_values, unique_values) - 1
  legend <- tibble(Original = unique_values, Code = encoded_values)
  return(legend)
}

#Create the legends for the columns
legend_Sexual_Dimorphism <- create_legend(data$Sexual_dimorphism)
legend_SD_Direction <- create_legend(data$Direction)
legend_Natal_coat <- create_legend(data$Natal_coat)
legend_Natal_coat_type <- create_legend(data$Natal_Coat_Type)
legend_Sexual_Dichrom <- create_legend(data$Sexual_dichromatism)
legend_Sexual_Dichrom_type <- create_legend(data$Sexual_dichromatism_type)
legend_Darker <- create_legend(data$Darker)


#Add column names
legend_Sexual_Dimorphism <- legend_Sexual_Dimorphism %>% mutate(Column = 'Sexual_Dimorphism')
legend_SD_Direction <- legend_SD_Direction %>% mutate(Column = 'SD_Direction')
legend_Natal_coat <- legend_Natal_coat %>% mutate(Column = 'Natal_Coat')
legend_Natal_coat_type <- legend_Natal_coat_type %>% mutate(Column = 'Natal_Coat_Type')
legend_Sexual_Dichrom <- legend_Sexual_Dichrom %>% mutate(Column = 'Sexual_Dichromatism')
legend_Sexual_Dichrom_type <- legend_Sexual_Dichrom %>% mutate(Column = 'Sexual_Dichrom_Type')
legend_Darker <- legend_Darker %>% mutate(Column = 'Darker')

#Combine the legends
combined_legends <- bind_rows(legend_Sexual_Dimorphism, legend_SD_Direction, legend_Natal_coat, legend_Natal_coat_type, legend_Sexual_Dichrom, legend_Sexual_Dichrom_type, legend_Darker)

#Create a csv for the legend
write.csv(combined_legends, "~/Github/LocksofLineage/data/combined_legends.csv", row.names = FALSE)
```

