---
title: "updated_names_analysis"
author: "Sarah E Taylor"
date: "2024-02-29"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Recoding the data

```{r Load-Libraries, include=FALSE}
#For data manipulation
library(dplyr)
#Library to read in the data file
library(readr)
#Library to run the phylogenetic analyses
library(ape)
#Library to clean and organize the data
library(tidyverse)
#Library to run the phylogenetic regressions
library(phylolm)
#Libary to plot the trees
library(ggtree)
#Library for other phylogenetic analyses
library(phytools)
#Libaries for heatmap
library(ggplot2)
library(gridExtra)
library(reshape2)
#Library for upset plot
library(ComplexUpset)
```

```{r Read-in-the-data}
data <- read_csv("data/Raw_Data/data_to_use.csv")
# 5 species were recorded as maybe having a natal coat because the sources were conflicting, for now they will be counted as not having a natal coat
# Cheirogaleus major, Macaca sylvanus, Procolobus pennantii, Presbytis femoralis, Pongo pygmaeus

```

```{r Binarize-the-yes-no-values}
data <- data %>%
  mutate(across(c(Sexual_dimorphism, Natal_coat, Sexual_dichromatism), ~if_else(. == "Yes", 1, 0)))
```


```{r Recode-natal-coat-variables}
# Reclassifying how we distinguish natal coat types
data <- data %>%
  mutate(Simple_Natal_Coat_Type = case_when(
    Natal_Coat_Type %in% c("Con to dad", "con to both", "con to mom") ~ "conspicuous",
    Natal_Coat_Type == "incon" ~ "inconspicuous",
    TRUE ~ "none"  # This will catch all other cases not specified above
  ))

# Add a column with all conspicuous natal coats as 1 and inconspicuous as 0
data <- data %>%
  mutate(
    Natal_Coat_Conspicuous = ifelse(Simple_Natal_Coat_Type == "conspicuous", 1, 0),
    Natal_Coat_Inconspicuous = ifelse(Simple_Natal_Coat_Type == "inconspicuous", 1, 0),
    Natal_Coat_Present = ifelse(Simple_Natal_Coat_Type %in% c("conspicuous", "inconspicuous"), 1, 0)
  )

#Natal coats can be inconspicuous (close in color to parents) or conspicuous (obviously a different color). #When they are conspicuous they can be contrasting to either the mothers coats or the fathers or both. 
```

```{r Recode-Maturation-Color-Change-Variables}
# This is recoding the different types of conspicuous natal coats and sexual dichromatism from separate traits into a continuous change ie infant -> adult female (change/no change), infant -> adult male (change/no change), if both change is another category. If a natal coat is conspicuous to dad it is similar or inconspicuous to mom so the males change when they mature.

data <- data %>%
  mutate(Maturation_Color_Change = case_when(
    Natal_Coat_Type == "Con to dad" ~ "Males only",
    Natal_Coat_Type == "con to both" ~ "Both", 
    Natal_Coat_Type == "con to mom" ~ "Females only",
    TRUE ~ "None"))

# Add binary columns for the different maturation changes
data <- data %>%
  mutate(Maturation_Males_Only = ifelse(Maturation_Color_Change == "Males only", 1, 0),
         Maturation_Females_Only = ifelse(Maturation_Color_Change == "Females only", 1, 0),
         Maturation_Both = ifelse(Maturation_Color_Change == "Both", 1, 0),
         Maturation_None = ifelse(Maturation_Color_Change == "None", 1, 0))
```

```{r Recode-Sexual-Dichromatism-Variables}
data <- data %>%
  mutate(Sexual_Dichromatism_Complete = ifelse(Sexual_dichromatism_type == "Complete", 1, 0),
         Sexual_Dichromatism_Partial = ifelse(Sexual_dichromatism_type == "Partial", 1, 0),
         Sexual_Dichromatism_Present = ifelse(Sexual_dichromatism_type %in% c("Complete", "Partial"), 1, 0))
```

```{r Save-recoded-data-set}
write_csv(data, "data/recoded_data.csv")
```

# Format data for phylolm
```{r Read-Mammal-Tree-Upham, echo=FALSE}
#read in mammal tree
mammaltree <- read.tree("data/Raw_Data/MamPhy_BDvr_Completed_v2_tree0000.tre")
summary(mammaltree)
```


```{r Read-Masters-Binary-Data, echo=FALSE}
#read in the data
Binary_traits <- read_csv("data/recoded_data.csv")
head(Binary_traits)
```

```{r Format-Binary-Data-SpeciesNames}
#combine genus and species names and capitalize first letter
Binary_traits_combined = Binary_traits %>% unite("species",`Genus`, `species`) %>% mutate(species = str_to_title(species))
head(Binary_traits_combined)
```

```{r Prune-Tree-For-Species-in-Data}
# prune tree for species in data
species_not_in_tree=setdiff(mammaltree$tip.label, Binary_traits_combined$species)
pruned.tree<-drop.tip(mammaltree,species_not_in_tree)
summary(pruned.tree)
```

```{r Prune-Data-For-Species-From-Tree}
#prune data for species in tree
data_pruned <- Binary_traits_combined %>% filter(species %in% pruned.tree$tip.label)
head(data_pruned)
```

```{r Re-order-Data-to-match-tiplabels}
# get the order of the tip labels
tip_order <- pruned.tree$tip.label

# Match the order of species in the dataframe to the order of tip labels in the tree
ordered_indices <- match(tip_order, data_pruned$species)

# Reorder the dataframe based on the indices obtained
data_pruned_ordered <- Binary_traits_combined[ordered_indices, ]
```

```{r Format-Data-Phylolm}
#put data into useful form for phylolm
colnames(data_pruned_ordered) = gsub(" ", "_", colnames(data_pruned))
data_pruned_rownames = column_to_rownames(data_pruned_ordered, var = "species")
head(data_pruned_rownames)
```

```{r Save-Data-Formatted-for-phylolm}
write_csv(data_pruned_rownames, "data/data_formatted_phylolm.csv")
```

# Run the Logistic Regressions
```{r Functions-for-phylolm-and-odds-ratio}
# Create the phylolm function
run_phylolm_analyses <- function(data, phylo_tree, independent_vars, dependent_vars){ 
  results <- list()
  for (ind_var in independent_vars){
    for (dep_var in dependent_vars){
      formula <- as.formula(paste(dep_var, "~", ind_var))
      model <- phyloglm(formula, data=data, phy=phylo_tree, method = "logistic_MPLE")
      results[[paste(ind_var, dep_var, sep = "_vs_")]] <- summary(model)
  }
  }
  return(results)
}

#Function to extract model stats, odds ratio, p-value
extract_model_stats <- function(results_list, independent_vars, dependent_vars) {
  # Initialize a matrix to store the odds ratios
  odds_ratios <- matrix(NA, 
                        nrow = length(dependent_vars), 
                        ncol = length(independent_vars),
                        dimnames = list(dependent_vars, independent_vars))
  p_values <- matrix(NA, 
                     nrow = length(dependent_vars), 
                     ncol = length(independent_vars),
                     dimnames = list(dependent_vars, independent_vars))
  
  # Iterate through the results to extract coefficients
  for (dep_var in dependent_vars) {
    for (ind_var in independent_vars) {
      # Construct the result name used as the key in the results list
      result_key <- paste(ind_var, dep_var, sep = "_vs_")
      
      # Check if the result exists and extract the coefficients
      if (result_key %in% names(results_list)) {
        # Extract the model summary
        model_summary <- results_list[[result_key]]
        
        # Check if the model summary is indeed a list with a coefficients data frame
        if (is.list(model_summary) && "coefficients" %in% names(model_summary)) {
          # Extract the estimate for the independent variable
          if (ind_var %in% rownames(model_summary$coefficients)) {
            estimate <- model_summary$coefficients[ind_var, "Estimate"]
            p_value <- model_summary$coefficients[ind_var, "p.value"]
            odds_ratios[dep_var, ind_var] <- exp(estimate)
            p_values[dep_var, ind_var] <- p_value
          }
        }
      }
    }
  }
  
  return(list(odds_ratios = odds_ratios, p_values = p_values))
}
```

```{r Ind-Natal-Coats-Dep-Sexual-Dichromatism, warning=FALSE}
data <- data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous", "Natal_Coat_Present")
dependent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both")
Natal_on_Dichromatism_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
Natal_on_Dichromatism_model_stats <- extract_model_stats(Natal_on_Dichromatism_results, independent_vars, dependent_vars)
Natal_on_Dichromatism_odds_ratio_matrix <- Natal_on_Dichromatism_model_stats$odds_ratios
Natal_on_Dichromatism_p_value_matrix <- Natal_on_Dichromatism_model_stats$p_values
```

```{r Ind-Sexual-Dichromatism-Dep-Natal-Coats, warning=FALSE}
data <- data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both")
dependent_vars <- c("Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous", "Natal_Coat_Present")
Dichromatism_on_Natal_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
Dichromatism_on_Natal_model_stats <- extract_model_stats(Dichromatism_on_Natal_results, independent_vars, dependent_vars)
Dichromatism_on_Natal_odds_ratio_matrix <- Dichromatism_on_Natal_model_stats$odds_ratios
Dichromatism_on_Natal_p_value_matrix <- Dichromatism_on_Natal_model_stats$p_values
```

```{r Ind-Sexual-Dimorphism-Dep-Natal-and-Dichromatism, warning=FALSE}
data <- data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Sexual_dimorphism", "Size_Dimorphism")
dependent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both","Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous", "Natal_Coat_Present")
Dimorphism_on_Natal_and_Dichrom_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
Dimorphism_on_Natal_and_Dichrom_model_stats <- extract_model_stats(Dimorphism_on_Natal_and_Dichrom_results, independent_vars, dependent_vars)
Dimorphism_on_Natal_and_Dichrom_odds_ratio_matrix <- Dimorphism_on_Natal_and_Dichrom_model_stats$odds_ratios
Dimorphism_on_Natal_and_Dichrom_p_value_matrix <- Dimorphism_on_Natal_and_Dichrom_model_stats$p_values
```

```{r Natal-and-Dichrom-on-Dimorphism}
data <- data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both","Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous", "Natal_Coat_Present") 
dependent_vars <- c("Sexual_dimorphism", "Size_Dimorphism")
Natal_and_Dichrom_on_Dimorphism_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
Natal_and_Dichrom_on_Dimorphism_model_stats <- extract_model_stats(Natal_and_Dichrom_on_Dimorphism_results, independent_vars, dependent_vars)
Natal_and_Dichrom_on_Dimorphism_odds_ratio_matrix <- Natal_and_Dichrom_on_Dimorphism_model_stats$odds_ratios
Natal_and_Dichrom_on_Dimorphism_p_value_matrix <- Natal_and_Dichrom_on_Dimorphism_model_stats$p_values
```

# Visualizations
```{r Heatmaps, fig.width=16, fig.height=4, dpi=300}
# Function to determine significance symbols based on p-values
get_significance_symbol <- function(p_value) {
  ifelse(p_value < 0.001, '***',
         ifelse(p_value < 0.01, '**',
                ifelse(p_value < 0.05, '*', '')))
}
  
# Function to create a heatmap with significance symbols
create_heatmap <- function(odds_ratio_matrix, p_value_matrix, title_prefix) {
  # Melt the odds ratio matrix and p-value matrix into data frames
  df_odds <- melt(odds_ratio_matrix)
  df_pvals <- melt(p_value_matrix)
  
  # Add column names for merging
  colnames(df_odds) <- c("RowTraits", "ColTraits", "value")
  colnames(df_pvals) <- c("RowTraits", "ColTraits", "p_value")
  
  # Merge the data frames
  df_merged <- merge(df_odds, df_pvals, by = c("RowTraits", "ColTraits"))
  
  # Apply logarithmic transformation to the odds ratio values
  df_merged$value_log <- log(df_merged$value + 1)
  
  # Calculate significance symbols
  df_merged$significance <- get_significance_symbol(df_merged$p_value)
  
  # Create the heatmap
  heatmap <- ggplot(df_merged, aes(RowTraits, ColTraits, fill = value_log)) + 
    geom_tile() +
    scale_fill_gradient2(low = "white", high = "red", mid = "blue", midpoint = log(1 + 1), space = "Lab", name="Log Odds Ratio") +
    geom_text(aes(label = sprintf("%.2f", value)), size = 3, vjust = -1) +
    geom_text(aes(label = significance), size = 3, vjust = 1) +
    theme_minimal() +
    labs(title = paste(title_prefix, "Log Scale"), x = "Dependent Characteristics", y = "Independent Characteristics") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text.y = element_text(angle = 45, vjust = 1))
  
  return(heatmap)
}

# usage:
heatmap1 <- create_heatmap(Natal_on_Dichromatism_odds_ratio_matrix, Natal_on_Dichromatism_p_value_matrix, "Effect of Natal Coat on Sexual Dichromatism")
heatmap2 <- create_heatmap(Dichromatism_on_Natal_odds_ratio_matrix, Dichromatism_on_Natal_p_value_matrix, "Effect of Sexual Dichromatism on Natal Coat")
heatmap3 <- create_heatmap( Dimorphism_on_Natal_and_Dichrom_odds_ratio_matrix, Dimorphism_on_Natal_and_Dichrom_p_value_matrix, "Sexual Dimorphism Impacting other Characteristics")
heatmap4 <- create_heatmap( Natal_and_Dichrom_on_Dimorphism_odds_ratio_matrix, Natal_and_Dichrom_on_Dimorphism_p_value_matrix, "other Characteristics Impacting Sexual Dimorphism")
# Print heatmaps side by side
grid.arrange(heatmap1, heatmap2, heatmap3, heatmap4, ncol = 2, nrow = 2)

```

```{r Heatmap-with-colored-significance, fig.width=16, fig.height=4, dpi=300}
create_signif_heatmap <- function(odds_ratio_matrix, p_value_matrix, title_prefix, signif_level = 0.05) {
  # Melt the odds ratio matrix and p-value matrix into data frames
  df_odds <- melt(odds_ratio_matrix)
  df_pvals <- melt(p_value_matrix)
  
  # Add column names for merging
  colnames(df_odds) <- c("RowTraits", "ColTraits", "value")
  colnames(df_pvals) <- c("RowTraits", "ColTraits", "p_value")
  
  # Merge the data frames
  df_merged <- merge(df_odds, df_pvals, by = c("RowTraits", "ColTraits"))
  
  # Apply logarithmic transformation to the odds ratio values
  df_merged$value_log <- log(df_merged$value + 1)
  
  # Calculate significance symbols
  df_merged$significance <- get_significance_symbol(df_merged$p_value)
  
  # Create a new column for the fill color based on significance
  df_merged$fill_color <- ifelse(df_merged$p_value < signif_level, 'significant', 'not_significant')
  
  # Create the heatmap
  heatmap <- ggplot(df_merged, aes(RowTraits, ColTraits)) + 
    geom_tile(aes(fill = fill_color), color = "black", size = 0.5) + # Add borders here
    scale_fill_manual(values = c('significant' = 'purple', 'not_significant' = 'grey')) +
    geom_text(aes(label = sprintf("%.2f", value)), size = 3, vjust = 1, color = "white") + # Removed color mapping for text labels
    geom_text(aes(label = significance), size = 3, vjust = 0.5, color = "black") + # Removed color mapping for significance labels
    theme_minimal() +
    labs(title = paste(title_prefix, "Log Scale"), x = "Dependent Characteristics", y = "Independent Characteristics") +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      axis.text.y = element_text(angle = 45, vjust = 1)
    ) 
  
  return(heatmap)
}

signif_level <- 0.05

heatmapS1 <- create_signif_heatmap(Natal_on_Dichromatism_odds_ratio_matrix, Natal_on_Dichromatism_p_value_matrix, "Effect of Natal Coat on Sexual Dichromatism")
heatmapS2 <- create_signif_heatmap(Dichromatism_on_Natal_odds_ratio_matrix, Dichromatism_on_Natal_p_value_matrix, "Effect of Sexual Dichromatism on Natal Coat")
heatmapS3 <- create_signif_heatmap( Dimorphism_on_Natal_and_Dichrom_odds_ratio_matrix, Dimorphism_on_Natal_and_Dichrom_p_value_matrix, "Sexual Dimorphism Impacting other Characteristics")
heatmapS4 <- create_signif_heatmap( Natal_and_Dichrom_on_Dimorphism_odds_ratio_matrix, Natal_and_Dichrom_on_Dimorphism_p_value_matrix, "other Characteristics Impacting Sexual Dimorphism")
# Print heatmaps side by side
grid.arrange(heatmapS1, heatmapS2, heatmapS3, heatmapS4, ncol = 2, nrow = 2)

```

```{r heatmap-grey-out-non-sig-still-heatmap-for-the-rest, fig.width=16, fig.height=4, dpi=300}
create_heatmap_non_sig_na_grey <- function(odds_ratio_matrix, p_value_matrix, title_prefix, signif_level = 0.05) {
  # Melt the odds ratio matrix and p-value matrix into data frames
  df_odds <- melt(odds_ratio_matrix)
  df_pvals <- melt(p_value_matrix)
  
  # Add column names for merging
  colnames(df_odds) <- c("RowTraits", "ColTraits", "value")
  colnames(df_pvals) <- c("RowTraits", "ColTraits", "p_value")
  
  # Merge the data frames
  df_merged <- merge(df_odds, df_pvals, by = c("RowTraits", "ColTraits"))
  
  # Apply logarithmic transformation to the odds ratio values
  df_merged$value_log <- log(df_merged$value + 1)
  
  # Calculate significance symbols and determine which values to grey out
  df_merged$significance <- get_significance_symbol(df_merged$p_value)
  df_merged$fill <- ifelse(df_merged$p_value < signif_level, df_merged$value_log, NA)
  
  # Create the heatmap
  heatmap <- ggplot(df_merged, aes(RowTraits, ColTraits)) + 
    geom_tile(aes(fill = fill), color = "black", size = 0.3) +
    scale_fill_gradient2(low = "white", high = "red", mid = "blue",
                         midpoint = log(1 + 1), space = "Lab", name="Log Odds Ratio",
                         na.value = "grey", limits = range(df_merged$value_log, na.rm = TRUE)) +
    geom_text(aes(label = ifelse(is.na(fill), "", sprintf("%.2f", value))), size = 3, vjust = -1) +
    geom_text(aes(label = significance), size = 3, vjust = 1) +
    theme_minimal() +
    labs(title = paste(title_prefix, "Log Scale"), x = "Dependent Characteristics", y = "Independent Characteristics") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text.y = element_text(angle = 45, vjust = 1))
  
  return(heatmap)
}

heatmapSG1 <- create_heatmap_non_sig_na_grey(Natal_on_Dichromatism_odds_ratio_matrix, Natal_on_Dichromatism_p_value_matrix, "Effect of Natal Coat on Sexual Dichromatism")
heatmapSG2 <- create_heatmap_non_sig_na_grey(Dichromatism_on_Natal_odds_ratio_matrix, Dichromatism_on_Natal_p_value_matrix, "Effect of Sexual Dichromatism on Natal Coat")
heatmapSG3 <- create_heatmap_non_sig_na_grey( Dimorphism_on_Natal_and_Dichrom_odds_ratio_matrix, Dimorphism_on_Natal_and_Dichrom_p_value_matrix, "Sexual Dimorphism Impacting other Characteristics")
heatmapSG4 <- create_heatmap_non_sig_na_grey( Natal_and_Dichrom_on_Dimorphism_odds_ratio_matrix, Natal_and_Dichrom_on_Dimorphism_p_value_matrix, "other Characteristics Impacting Sexual Dimorphism")
# Print heatmaps side by side
grid.arrange(heatmapSG1, heatmapSG2, heatmapSG3, heatmapSG4, ncol = 2, nrow = 2)
```

```{r Upset-Plot, fig.width=9, fig.height=6, dpi=300}
# Define the traits
set_attributes <- c(
  'Natal_Coat_Conspicuous', 
  'Size_Dimorphism',
  'Sexual_Dichromatism_Complete', 
  'Sexual_Dichromatism_Partial',
  'Maturation_Males_Only',
  'Maturation_Females_Only',
  'Maturation_Both',
  'Sexual_dimorphism')

# Create the plot
upset(
    data_pruned_rownames,
    set_attributes,
    base_annotations=list(
        'Intersection size'=intersection_size(
            counts=TRUE,
            mapping=aes(fill=family) 
        ) 
    ),
    width_ratio=0.1
)
```

```{r Venn-diagram-of-traits}
library(ggvenn)

# Convert the specified columns to logical
data_pruned_rownames$Natal_coat <- as.logical(data_pruned_rownames$Natal_coat)
data_pruned_rownames$Sexual_dichromatism <- as.logical(data_pruned_rownames$Sexual_dichromatism)
data_pruned_rownames$Sexual_dimorphism <- as.logical(data_pruned_rownames$Sexual_dimorphism)

# Create the Venn diagram 
ggvenn(data_pruned_rownames, c("Natal_coat", "Sexual_dichromatism", "Sexual_dimorphism"))

#Venn to just show natal coat characteristics "species inconspicuous and conspicuous relative to total species with and without natal coats

data_pruned_rownames$Natal_Coat_Conspicuous <- as.logical(data_pruned_rownames$Natal_Coat_Conspicuous)
data_pruned_rownames$Natal_Coat_Inconspicuous <- as.logical(data_pruned_rownames$Natal_Coat_Inconspicuous)

ggvenn(data_pruned_rownames, c("Sexual_dichromatism", "Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous"))

```

# Subset Data to only include species that have a natal coat

```{r Subset-Data-to-Species-with-Natal-Coats}
natal_coat_subset <- Binary_traits_combined[Binary_traits_combined$Natal_coat == TRUE, ]

```

```{r Prune-Tree-For-Species-in-Data-with-Natal-Coats}
# prune tree for species in data
nc_species_not_in_tree=setdiff(mammaltree$tip.label, natal_coat_subset$species)
nc_pruned.tree<-drop.tip(mammaltree,nc_species_not_in_tree)
summary(nc_pruned.tree)
```

```{r Prune-Natal-Coat-Data-For-Species-From-Tree}
#prune data for species in tree
nc_data_pruned <- natal_coat_subset %>% filter(species %in% nc_pruned.tree$tip.label)
head(nc_data_pruned)
```

```{r Re-order-Natal-Coat-Data-to-match-tiplabels}
# get the order of the tip labels
nc_tip_order <- nc_pruned.tree$tip.label

# Match the order of species in the dataframe to the order of tip labels in the tree
nc_ordered_indices <- match(nc_tip_order, nc_data_pruned$species)

# Reorder the dataframe based on the indices obtained
nc_data_pruned_ordered <- natal_coat_subset[nc_ordered_indices, ]
```

```{r Format-Natal-Coat-Data-Phylolm}
#put data into useful form for phylolm
colnames(nc_data_pruned_ordered) = gsub(" ", "_", colnames(nc_data_pruned))
nc_data_pruned_rownames = column_to_rownames(nc_data_pruned_ordered, var = "species")
head(nc_data_pruned_rownames)
```

```{r Subset-Ind-Natal-Coats-Dep-Sexual-Dichromatism, warning=FALSE}
data <- nc_data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous")
dependent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both")
subset_Natal_on_Dichromatism_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
subset_Natal_on_Dichromatism_model_stats <- extract_model_stats(subset_Natal_on_Dichromatism_results, independent_vars, dependent_vars)
subset_Natal_on_Dichromatism_odds_ratio_matrix <- subset_Natal_on_Dichromatism_model_stats$odds_ratios
subset_Natal_on_Dichromatism_p_value_matrix <- subset_Natal_on_Dichromatism_model_stats$p_values
```

```{r Subset-Ind-Sexual-Dichromatism-Dep-Natal-Coats, warning=FALSE}
data <- nc_data_pruned_rownames
phylo_tree <- pruned.tree
independent_vars <- c("Sexual_Dichromatism_Complete", "Sexual_Dichromatism_Partial", "Sexual_Dichromatism_Present", "Maturation_Males_Only", "Maturation_Females_Only", "Maturation_Both")
dependent_vars <- c("Natal_Coat_Conspicuous", "Natal_Coat_Inconspicuous")
subset_Dichromatism_on_Natal_results <- run_phylolm_analyses(data,phylo_tree, independent_vars, dependent_vars)
subset_Dichromatism_on_Natal_model_stats <- extract_model_stats(subset_Dichromatism_on_Natal_results, independent_vars, dependent_vars)
subset_Dichromatism_on_Natal_odds_ratio_matrix <- subset_Dichromatism_on_Natal_model_stats$odds_ratios
subset_Dichromatism_on_Natal_p_value_matrix <- subset_Dichromatism_on_Natal_model_stats$p_values
```

```{r subset-heatmaps, fig.width=16, fig.height=4, dpi=300}
heatmapSubset1 <- create_heatmap_non_sig_na_grey(subset_Natal_on_Dichromatism_odds_ratio_matrix, subset_Natal_on_Dichromatism_p_value_matrix, "Subset Effect of Natal Coat on Sexual Dichromatism")
heatmapSubset2 <- create_heatmap_non_sig_na_grey(subset_Dichromatism_on_Natal_odds_ratio_matrix, subset_Dichromatism_on_Natal_p_value_matrix, "Subset Effect of Sexual Dichromatism on Natal Coat")

# Print heatmaps side by side
grid.arrange(heatmapSubset1, heatmapSubset2, ncol = 2)
```

